name: Quality Checks

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  quality-checks:
    name: Quality Checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        if: always()
        run: npm run build

      - name: Run tests
        if: always()
        run: npm test

      - name: Generate coverage
        if: always()
        run: npm run test:coverage

      - name: Validate coverage
        if: always()
        run: node scripts/coverage-check.js

      - name: Check formatting
        if: always()
        run: npm run format:check

      - name: Lint code
        if: always()
        run: npm run lint

      - name: Upload coverage reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: coverage/
          retention-days: 30

      - name: Quality gate status
        if: always()
        run: |
          if [ "${{ job.status }}" = "success" ]; then
            echo "## ✅ All Quality Checks Passed!" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "| Check | Status |" >> $GITHUB_STEP_SUMMARY
            echo "|-------|--------|" >> $GITHUB_STEP_SUMMARY
            echo "| Build | ✅ Passed |" >> $GITHUB_STEP_SUMMARY
            echo "| Tests | ✅ Passed |" >> $GITHUB_STEP_SUMMARY
            echo "| Coverage | ✅ Passed |" >> $GITHUB_STEP_SUMMARY
            echo "| Formatting | ✅ Passed |" >> $GITHUB_STEP_SUMMARY
            echo "| Linting | ✅ Passed |" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "🎉 Ready to merge!" >> $GITHUB_STEP_SUMMARY
            echo "✅ Quality gate: PASSED"
            exit 0
          else
            echo "## ❌ Quality Checks Failed" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "Please check the failed steps above and fix the issues." >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "### 🔧 Quick Fixes" >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`bash" >> $GITHUB_STEP_SUMMARY
            echo "npm run format      # Fix formatting issues" >> $GITHUB_STEP_SUMMARY
            echo "npm run lint:fix    # Fix linting issues" >> $GITHUB_STEP_SUMMARY
            echo "npm test            # Run tests locally" >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
            echo "" >> $GITHUB_STEP_SUMMARY
            echo "💡 **Tip**: Run all checks locally before pushing:" >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`bash" >> $GITHUB_STEP_SUMMARY
            echo "npm run build && npm test && npm run format:check && npm run lint" >> $GITHUB_STEP_SUMMARY
            echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
            echo "❌ Quality gate: FAILED"
            exit 1
          fi
